alias init='sudo service docker init'
alias get_ip='ip address | grep "inet.*eth0" | grep -E "[0-9]([0-9.])+[0-9]" -o | head -n 1'

alias todockerfiles='cd /mnt/c/Users/aymen/Projects/Dockerfiles'
alias toprojectdir='cd $PROJECT_DIR'
alias nbhere='export PROJECT_DIR=$(pwd)'
alias nbin='export PROJECT_DIR=$1'
