name: pytorch-notebook
channels:
    - anaconda
    - conda-forge
dependencies:
    - python=3.8
    - pillow
    - matplotlib
    - numpy
    - pytest
    - jupyter
    - docopt
    - pyyaml
    - protobuf
    - grpcio
    - pandas
    - scipy
    - ipykernel
